# typed: strict
# Generated by bin/generate-sorbet-rbi. Do not edit it by hand.

module Commerce
  module Resources
    class Apps
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::CreateApplicationRequest, Commerce::Types::Payload)).returns(Commerce::Models::CreateApplicationResponse) }
      def create(payload); end

      sig { returns(Commerce::Models::LookupApplicationResponse) }
      def lookup(); end

      sig { params(payload: T.any(Commerce::Models::UpdateApplicationRequest, Commerce::Types::Payload)).returns(Commerce::Models::UpdateApplicationResponse) }
      def update(payload); end
    end

    class BalanceTransactions
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(transaction_id: String).returns(Commerce::Models::BalanceTransactionResponse) }
      def lookup(transaction_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageBalanceTransactionsRequest, Commerce::Types::Payload))).returns(Commerce::Models::BalanceTransactionPageResponse) }
      def page(payload = nil); end
    end

    class Balances
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { returns(Commerce::Models::BalanceSnapshotResponse) }
      def get(); end
    end

    class Broadcasts
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(broadcast_id: String).returns(Commerce::Models::BroadcastCancelResponse) }
      def cancel(broadcast_id:); end

      sig { params(broadcast_id: String).returns(Commerce::Models::LookupBroadcastResponse) }
      def lookup(broadcast_id:); end
    end

    class Chimes
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::BroadcastRequest, Commerce::Types::Payload)).returns(Commerce::Models::BroadcastResponse) }
      def broadcast(payload); end

      sig { params(chime_id: String).returns(Commerce::Models::ChimeResponse) }
      def lookup(chime_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageChimesRequest, Commerce::Types::Payload))).returns(Commerce::Models::PageChimesResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::ScheduleChimeRequest, Commerce::Types::Payload)).returns(Commerce::Models::ScheduleResponse) }
      def schedule(payload); end

      sig { params(payload: T.any(Commerce::Models::SendChimeRequest, Commerce::Types::Payload)).returns(Commerce::Models::ChimeResponse) }
      def send(payload); end
    end

    class Customers
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::CreateCustomerRequest, Commerce::Types::Payload)).returns(Commerce::Models::CustomerResponse) }
      def create(payload); end

      sig { params(customer_id: String).returns(Commerce::Models::CustomerResponse) }
      def lookup(customer_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageCustomersRequest, Commerce::Types::Payload))).returns(Commerce::Models::PageCustomersResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::UpdateCustomerRequest, Commerce::Types::Payload)).returns(Commerce::Models::CustomerResponse) }
      def update(payload); end
    end

    class FileLinks
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::CreateFileLinkRequest, Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::CreateFileLinkResponse) }
      def create(payload, idempotency_key: nil); end

      sig { params(id: String).returns(Commerce::Models::FileLinkResponse) }
      def lookup(id:); end

      sig { params(url: String, save_to: T.nilable(String)).returns(Commerce::FileDownload) }
      def open(url, save_to: nil); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageFileLinksRequest, Commerce::Types::Payload))).returns(Commerce::Models::FileLinkPageResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::RevokeFileLinkRequest, Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::FileLinkResponse) }
      def revoke(payload, idempotency_key: nil); end

      private

      sig { params(idempotency_key: T.nilable(String)).returns(Commerce::Types::Headers) }
      def headers(idempotency_key); end
    end

    class FileReferences
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::FileReferenceReconcileRequest, Commerce::Types::Payload)).returns(Commerce::Models::FileReferenceReconcileResponse) }
      def reconcile(payload); end
    end

    class Files
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(file_id: String, disposition: T.nilable(String)).returns(Commerce::FileDownload) }
      def contents(file_id:, disposition: nil); end

      sig { params(file: String, purpose: String, title: T.nilable(String), custom_data: T.nilable(Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::FileResponse) }
      def create(file:, purpose:, title: nil, custom_data: nil, idempotency_key: nil); end

      sig { params(file_id: String).returns(Commerce::Models::FileResponse) }
      def delete(file_id:); end

      sig { params(file_id: String).returns(Commerce::Models::FileResponse) }
      def lookup(file_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageFilesRequest, Commerce::Types::Payload))).returns(Commerce::Models::FilePageResponse) }
      def page(payload = nil); end
    end

    class FinancialAccounts
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::FinancialAccountCreateRequest, Commerce::Types::Payload)).returns(Commerce::Models::ConnectFinancialAccountResponse) }
      def connect(payload); end

      sig { params(payload: T.any(Commerce::Models::FinancialAccountCreateRequest, Commerce::Types::Payload)).returns(Commerce::Models::CreateFinancialAccountResponse) }
      def create(payload); end

      sig { params(account_id: String).returns(Commerce::Models::DisableFinancialAccountPullResponse) }
      def disable_pull(account_id:); end

      sig { params(account_id: String, unset_as_payout_destination: T.nilable(T::Boolean)).returns(Commerce::Models::DisableFinancialAccountPushResponse) }
      def disable_push(account_id:, unset_as_payout_destination: nil); end

      sig { params(account_id: String, unset_as_payout_destination: T.nilable(T::Boolean)).returns(Commerce::Models::DisconnectFinancialAccountResponse) }
      def disconnect(account_id:, unset_as_payout_destination: nil); end

      sig { params(account_id: String).returns(Commerce::Models::EnableFinancialAccountPullResponse) }
      def enable_pull(account_id:); end

      sig { params(account_id: String).returns(Commerce::Models::EnableFinancialAccountPushResponse) }
      def enable_push(account_id:); end

      sig { params(account_id: String).returns(Commerce::Models::LookupFinancialAccountResponse) }
      def lookup(account_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::FinancialAccountPageRequest, Commerce::Types::Payload))).returns(Commerce::Models::PageFinancialAccountsResponseInline) }
      def page(payload = nil); end

      sig { params(account_id: String).returns(Commerce::Models::ReconnectFinancialAccountResponse) }
      def reconnect(account_id:); end

      sig { params(payload: T.any(Commerce::Models::FinancialAccountUpdateRequest, Commerce::Types::Payload)).returns(Commerce::Models::UpdateFinancialAccountResponse) }
      def update(payload); end
    end

    class Keys
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String)).returns(Commerce::Models::DestroySecretKeyResponse) }
      def destroy(secret_key_id: nil, key_id: nil, id: nil); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::GenerateSecretKeyRequest, Commerce::Types::Payload))).returns(Commerce::Models::GenerateSecretKeyResponse) }
      def generate(payload = nil); end

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String)).returns(Commerce::Models::LookupSecretKeyResponse) }
      def lookup(secret_key_id: nil, key_id: nil, id: nil); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageSecretKeysRequest, Commerce::Types::Payload))).returns(Commerce::Models::PageSecretKeysResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::UpdateSecretKeyRequest, Commerce::Types::Payload)).returns(Commerce::Models::UpdateSecretKeyResponse) }
      def update(payload); end

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String), options: Commerce::Types::Payload).returns(Commerce::Models::SecretKeyUsageResponse) }
      def usage(secret_key_id: nil, key_id: nil, id: nil, **options); end

      private

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String)).returns(Commerce::Types::Payload) }
      def identifier_payload(secret_key_id, key_id, id); end
    end

    class MessageTemplates
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(template_id: String, idempotency_key: T.nilable(String)).returns(Commerce::Models::MessageTemplateEnvelope) }
      def archive(template_id:, idempotency_key: nil); end

      sig { params(payload: T.any(Commerce::Models::CreateMessageTemplateRequest, Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::MessageTemplateEnvelope) }
      def create(payload, idempotency_key: nil); end

      sig { params(template_id: String).returns(Commerce::Models::MessageTemplateEnvelope) }
      def lookup(template_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageMessageTemplatesRequest, Commerce::Types::Payload))).returns(Commerce::Models::MessageTemplatesPageEnvelope) }
      def page(payload = nil); end

      sig { params(template_id: String, idempotency_key: T.nilable(String)).returns(Commerce::Models::MessageTemplateEnvelope) }
      def publish(template_id:, idempotency_key: nil); end

      sig { params(payload: T.any(Commerce::Models::RenderMessageTemplatePreviewRequest, Commerce::Types::Payload)).returns(Commerce::Models::RenderMessageTemplatePreviewResponse) }
      def render_preview(payload); end

      sig { params(payload: T.any(Commerce::Models::UpdateMessageTemplateRequest, Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::MessageTemplateEnvelope) }
      def update(payload, idempotency_key: nil); end

      private

      sig { params(idempotency_key: T.nilable(String)).returns(Commerce::Types::Headers) }
      def idempotency_headers(idempotency_key); end
    end

    class Orders
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(order_id: String, request_meta: T.nilable(Commerce::Types::Payload)).returns(Commerce::Models::OrderResponse) }
      def cancel(order_id:, request_meta: nil); end

      sig { params(payload: T.any(Commerce::Models::CompleteOrderRequest, Commerce::Types::Payload)).returns(Commerce::Models::CompleteOrderResponse) }
      def complete(payload); end

      sig { params(payload: T.any(Commerce::Models::ConfirmPaymentRequest, Commerce::Types::Payload)).returns(Commerce::Models::OrderResponse) }
      def confirm_payment(payload); end

      sig { params(payload: T.any(T.any(Commerce::Models::CreateOrderNewCustomer, Commerce::Models::CreateOrderExistingCustomer), Commerce::Types::Payload)).returns(Commerce::Models::OrderResponse) }
      def create(payload); end

      sig { params(order_id: String, request_meta: T.nilable(Commerce::Types::Payload)).returns(Commerce::Models::FinalizeOrderResponse) }
      def finalize(order_id:, request_meta: nil); end

      sig { params(order_id: String, options: Commerce::Types::Payload).returns(Commerce::Models::OrderResponse) }
      def lookup(order_id:, **options); end

      sig { params(payload: T.any(T.any(Commerce::Models::CreateOrderNewCustomer, Commerce::Models::CreateOrderExistingCustomer), Commerce::Types::Payload)).returns(Commerce::Models::OrderResponse) }
      def new(payload); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageOrdersRequest, Commerce::Types::Payload))).returns(Commerce::Models::PageOrdersResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::PayOrderRequest, Commerce::Types::Payload)).returns(Commerce::Models::OrderResponse) }
      def pay(payload); end

      sig { params(payload: T.any(Commerce::Models::CreateRefundRequest, Commerce::Types::Payload)).returns(Commerce::Models::RefundResponse) }
      def refund(payload); end

      sig { params(order_id: String, request_meta: T.nilable(Commerce::Types::Payload)).returns(Commerce::Models::OrderResponse) }
      def request_confirmation(order_id:, request_meta: nil); end

      sig { params(order_id: String).returns(Commerce::Models::OrderDocumentDeliveryResponse) }
      def send_invoice(order_id:); end

      sig { params(order_id: String).returns(Commerce::Models::OrderDocumentDeliveryResponse) }
      def send_receipt(order_id:); end

      sig { params(payload: T.any(Commerce::Models::UpdateOrderRequest, Commerce::Types::Payload)).returns(Commerce::Models::OrderResponse) }
      def update(payload); end

      private

      sig { params(action: String, order_id: String).returns(Commerce::Types::Payload) }
      def stable_order_request_meta(action, order_id); end
    end

    class Otp
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: Commerce::Types::RequestBody).returns(Commerce::Models::CancelOTPResponse) }
      def cancel(payload); end

      sig { params(payload: T.any(Commerce::Models::InitiateOTPRequest, Commerce::Types::Payload)).returns(Commerce::Models::InitiateOTPResponse) }
      def initiate(payload); end

      sig { params(payload: T.any(Commerce::Models::LookupOTPRequest, Commerce::Types::Payload)).returns(Commerce::Models::LookupOTPResponse) }
      def lookup(payload); end

      sig { params(payload: T.any(Commerce::Models::VerifyOTPRequest, Commerce::Types::Payload)).returns(Commerce::Models::VerifyOTPResponse) }
      def verify(payload); end
    end

    class PaymentMethods
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payment_method_id: String).returns(Commerce::Models::ActivatePaymentMethodResponse) }
      def activate(payment_method_id:); end

      sig { params(payment_method_id: String).returns(Commerce::Models::ArchivePaymentMethodResponse) }
      def archive(payment_method_id:); end

      sig { params(payload: Commerce::Types::RequestBody).returns(Commerce::Models::PaymentMethodResponse) }
      def confirm_verification(payload); end

      sig { params(payment_method_id: String, request_meta: T.nilable(Commerce::Types::Payload)).returns(Commerce::Models::PaymentMethodDeleteResponse) }
      def delete(payment_method_id:, request_meta: nil); end

      sig { params(payment_method_id: String).returns(Commerce::Models::DisactivatePaymentMethodResponse) }
      def disactivate(payment_method_id:); end

      sig { params(payment_method_id: String).returns(Commerce::Models::LookupPaymentMethodResponse) }
      def lookup(payment_method_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PaymentMethodPageRequest, Commerce::Types::Payload))).returns(Commerce::Models::PaymentMethodPageResponse) }
      def page(payload = nil); end

      sig { returns(Commerce::Models::GetPaymentMethodSettingsResponse) }
      def settings(); end

      sig { params(payload: T.any(Commerce::Models::TokenizeMobileMoneyPaymentMethodRequest, Commerce::Types::Payload)).returns(Commerce::Models::TokenizePaymentMethodResponse) }
      def tokenize(payload); end

      sig { params(payment_method_id: String).returns(Commerce::Models::UnarchivePaymentMethodResponse) }
      def unarchive(payment_method_id:); end

      sig { params(payload: T.any(Commerce::Models::UpdatePaymentMethodRequest, Commerce::Types::Payload)).returns(Commerce::Models::UpdatePaymentMethodResponse) }
      def update(payload); end

      sig { params(payment_method_id: String, request_meta: T.nilable(Commerce::Types::Payload)).returns(Commerce::Models::PaymentMethodVerificationResponse) }
      def verify(payment_method_id:, request_meta: nil); end

      private

      sig { params(action: String, payment_method_id: String).returns(Commerce::Types::Payload) }
      def stable_payment_method_request_meta(action, payment_method_id); end
    end

    class Payouts
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payout_id: String).returns(Commerce::Models::CancelPayoutResponse) }
      def cancel(payout_id:); end

      sig { returns(Commerce::Models::DisableAutomaticPayoutsResponse) }
      def disable_automatic(); end

      sig { returns(Commerce::Models::PayoutSettingsResponse) }
      def disable_fx(); end

      sig { returns(Commerce::Models::EnableAutomaticPayoutsResponse) }
      def enable_automatic(); end

      sig { returns(Commerce::Models::PayoutSettingsResponse) }
      def enable_fx(); end

      sig { params(payout_id: String).returns(Commerce::Models::LookupPayoutResponse) }
      def lookup(payout_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PagePayoutsRequest, Commerce::Types::Payload))).returns(Commerce::Models::PagePayoutsResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::SchedulePayoutRequest, Commerce::Types::Payload)).returns(Commerce::Models::SchedulePayoutResponse) }
      def schedule(payload); end

      sig { params(destinations: T::Hash[String, String]).returns(Commerce::Models::SetPayoutDestinationsResponse) }
      def set_destinations(destinations:); end

      sig { returns(Commerce::Models::GetPayoutSettingsResponse) }
      def settings(); end
    end

    class Prices
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(price_id: String).returns(Commerce::Models::PriceResponse) }
      def activate(price_id:); end

      sig { params(price_id: String).returns(Commerce::Models::PriceResponse) }
      def archive(price_id:); end

      sig { params(payload: T.any(Commerce::Models::CreatePriceRequest, Commerce::Types::Payload)).returns(Commerce::Models::PriceResponse) }
      def create(payload); end

      sig { params(price_id: String).returns(Commerce::Models::PriceResponse) }
      def deactivate(price_id:); end

      sig { params(price_id: String).returns(Commerce::Models::PriceResponse) }
      def lookup(price_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PricePageRequest, Commerce::Types::Payload))).returns(Commerce::Models::PricePageResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::UpdatePriceRequest, Commerce::Types::Payload)).returns(Commerce::Models::PriceResponse) }
      def update(payload); end
    end

    class Products
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::AddProductPriceRequest, Commerce::Types::Payload)).returns(Commerce::Models::AddProductPriceResponse) }
      def add_price(payload); end

      sig { params(product_id: String).returns(Commerce::Models::ProductResponse) }
      def archive(product_id:); end

      sig { params(payload: T.any(Commerce::Models::CreateProductRequest, Commerce::Types::Payload)).returns(Commerce::Models::ProductResponse) }
      def create(payload); end

      sig { params(product_id: String).returns(Commerce::Models::ProductResponse) }
      def lookup(product_id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageProductsRequest, Commerce::Types::Payload))).returns(Commerce::Models::PageProductsResponse) }
      def page(payload = nil); end

      sig { params(product_id: String).returns(Commerce::Models::ProductResponse) }
      def publish(product_id:); end

      sig { params(payload: T.any(Commerce::Models::SetDefaultUnitPriceRequest, Commerce::Types::Payload)).returns(Commerce::Models::ProductResponse) }
      def set_default_unit_price(payload); end

      sig { params(product_id: String).returns(Commerce::Models::ProductResponse) }
      def unpublish(product_id:); end

      sig { params(payload: T.any(Commerce::Models::UpdateProductRequest, Commerce::Types::Payload)).returns(Commerce::Models::UpdateProductResponse) }
      def update(payload); end
    end

    class PurchaseIntents
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(id: String).returns(Commerce::Models::PurchaseIntentResponse) }
      def cancel(id:); end

      sig { params(payload: T.any(Commerce::Models::CreatePurchaseIntentRequest, Commerce::Types::Payload)).returns(Commerce::Models::PurchaseIntentResponse) }
      def create(payload); end

      sig { params(id: String).returns(Commerce::Models::PurchaseIntentResponse) }
      def lookup(id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PagePurchaseIntentsRequest, Commerce::Types::Payload))).returns(Commerce::Models::PagePurchaseIntentsResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::UpdatePurchaseIntentRequest, Commerce::Types::Payload)).returns(Commerce::Models::PurchaseIntentResponse) }
      def update(payload); end
    end

    class Refunds
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(refund_id: String).returns(Commerce::Models::RefundResponse) }
      def cancel(refund_id:); end

      sig { params(payload: T.any(Commerce::Models::CreateRefundRequest, Commerce::Types::Payload)).returns(Commerce::Models::RefundResponse) }
      def create(payload); end

      sig { params(refund_id: String).returns(Commerce::Models::RefundResponse) }
      def lookup(refund_id:); end

      sig { params(payload: T.any(Commerce::Models::PageRefundsRequest, Commerce::Types::Payload)).returns(Commerce::Models::RefundPageResponse) }
      def page(payload); end
    end

    class Schedules
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(schedule_id: String).returns(Commerce::Models::ScheduleCancelResponse) }
      def cancel(schedule_id:); end

      sig { params(schedule_id: String).returns(Commerce::Models::ScheduleLookupResponse) }
      def lookup(schedule_id:); end
    end

    class Spec
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { returns(Commerce::Models::ListCountrySpecsResponse) }
      def countries(); end
    end

    class UploadRequests
      sig { params(http: Commerce::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Commerce::Models::CancelUploadRequestRequest, Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::UploadRequestResponse) }
      def cancel(payload, idempotency_key: nil); end

      sig { params(payload: T.any(Commerce::Models::CreateUploadRequestRequest, Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::UploadRequestResponse) }
      def create(payload, idempotency_key: nil); end

      sig { params(upload_url: String, file: String).returns(Commerce::Models::FulfillUploadRequestResponse) }
      def fulfill(upload_url:, file:); end

      sig { params(id: String).returns(Commerce::Models::UploadRequestWithAttemptResponse) }
      def lookup(id:); end

      sig { params(payload: T.nilable(T.any(Commerce::Models::PageUploadRequestsRequest, Commerce::Types::Payload))).returns(Commerce::Models::UploadRequestPageResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Commerce::Models::ReviewUploadRequestAttemptRequest, Commerce::Types::Payload), idempotency_key: T.nilable(String)).returns(Commerce::Models::UploadRequestWithAttemptResponse) }
      def review(payload, idempotency_key: nil); end

      private

      sig { params(idempotency_key: T.nilable(String)).returns(Commerce::Types::Headers) }
      def headers(idempotency_key); end
    end
  end
end
