# typed: strict
# Generated by bin/generate-sorbet-rbi. Do not edit it by hand.

module Inttegro
  module Resources
    class Apps
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::CreateApplicationRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::CreateApplicationResponse) }
      def create(payload); end

      sig { returns(Inttegro::Models::LookupApplicationResponse) }
      def lookup(); end

      sig { params(payload: T.any(Inttegro::Models::UpdateApplicationRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::UpdateApplicationResponse) }
      def update(payload); end
    end

    class BalanceTransactions
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(transaction_id: String).returns(Inttegro::Models::BalanceTransactionResponse) }
      def lookup(transaction_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageBalanceTransactionsRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::BalanceTransactionPageResponse) }
      def page(payload = nil); end
    end

    class Balances
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { returns(Inttegro::Models::BalanceSnapshotResponse) }
      def get(); end
    end

    class Broadcasts
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(broadcast_id: String).returns(Inttegro::Models::BroadcastCancelResponse) }
      def cancel(broadcast_id:); end

      sig { params(broadcast_id: String).returns(Inttegro::Models::LookupBroadcastResponse) }
      def lookup(broadcast_id:); end
    end

    class Chimes
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::BroadcastRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::BroadcastResponse) }
      def broadcast(payload); end

      sig { params(chime_id: String).returns(Inttegro::Models::ChimeResponse) }
      def lookup(chime_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageChimesRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PageChimesResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::ScheduleChimeRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::ScheduleResponse) }
      def schedule(payload); end

      sig { params(payload: T.any(Inttegro::Models::SendChimeRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::ChimeResponse) }
      def send(payload); end
    end

    class Customers
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::CreateCustomerRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::CustomerResponse) }
      def create(payload); end

      sig { params(customer_id: String).returns(Inttegro::Models::CustomerResponse) }
      def lookup(customer_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageCustomersRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PageCustomersResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::UpdateCustomerRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::CustomerResponse) }
      def update(payload); end
    end

    class FileLinks
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::CreateFileLinkRequest, Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::CreateFileLinkResponse) }
      def create(payload, idempotency_key: nil); end

      sig { params(id: String).returns(Inttegro::Models::FileLinkResponse) }
      def lookup(id:); end

      sig { params(url: String, save_to: T.nilable(String)).returns(Inttegro::FileDownload) }
      def open(url, save_to: nil); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageFileLinksRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::FileLinkPageResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::RevokeFileLinkRequest, Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::FileLinkResponse) }
      def revoke(payload, idempotency_key: nil); end

      private

      sig { params(idempotency_key: T.nilable(String)).returns(Inttegro::Types::Headers) }
      def headers(idempotency_key); end
    end

    class FileReferences
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::FileReferenceReconcileRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::FileReferenceReconcileResponse) }
      def reconcile(payload); end
    end

    class Files
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(file_id: String, disposition: T.nilable(String)).returns(Inttegro::FileDownload) }
      def contents(file_id:, disposition: nil); end

      sig { params(file: String, purpose: String, title: T.nilable(String), custom_data: T.nilable(Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::FileResponse) }
      def create(file:, purpose:, title: nil, custom_data: nil, idempotency_key: nil); end

      sig { params(file_id: String).returns(Inttegro::Models::FileResponse) }
      def delete(file_id:); end

      sig { params(file_id: String).returns(Inttegro::Models::FileResponse) }
      def lookup(file_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageFilesRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::FilePageResponse) }
      def page(payload = nil); end
    end

    class FinancialAccounts
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::FinancialAccountCreateRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::ConnectFinancialAccountResponse) }
      def connect(payload); end

      sig { params(payload: T.any(Inttegro::Models::FinancialAccountCreateRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::CreateFinancialAccountResponse) }
      def create(payload); end

      sig { params(account_id: String).returns(Inttegro::Models::DisableFinancialAccountPullResponse) }
      def disable_pull(account_id:); end

      sig { params(account_id: String, unset_as_payout_destination: T.nilable(T::Boolean)).returns(Inttegro::Models::DisableFinancialAccountPushResponse) }
      def disable_push(account_id:, unset_as_payout_destination: nil); end

      sig { params(account_id: String, unset_as_payout_destination: T.nilable(T::Boolean)).returns(Inttegro::Models::DisconnectFinancialAccountResponse) }
      def disconnect(account_id:, unset_as_payout_destination: nil); end

      sig { params(account_id: String).returns(Inttegro::Models::EnableFinancialAccountPullResponse) }
      def enable_pull(account_id:); end

      sig { params(account_id: String).returns(Inttegro::Models::EnableFinancialAccountPushResponse) }
      def enable_push(account_id:); end

      sig { params(account_id: String).returns(Inttegro::Models::LookupFinancialAccountResponse) }
      def lookup(account_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::FinancialAccountPageRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PageFinancialAccountsResponseInline) }
      def page(payload = nil); end

      sig { params(account_id: String).returns(Inttegro::Models::ReconnectFinancialAccountResponse) }
      def reconnect(account_id:); end

      sig { params(payload: T.any(Inttegro::Models::FinancialAccountUpdateRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::UpdateFinancialAccountResponse) }
      def update(payload); end
    end

    class Keys
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String)).returns(Inttegro::Models::DestroySecretKeyResponse) }
      def destroy(secret_key_id: nil, key_id: nil, id: nil); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::GenerateSecretKeyRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::GenerateSecretKeyResponse) }
      def generate(payload = nil); end

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String)).returns(Inttegro::Models::LookupSecretKeyResponse) }
      def lookup(secret_key_id: nil, key_id: nil, id: nil); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageSecretKeysRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PageSecretKeysResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::UpdateSecretKeyRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::UpdateSecretKeyResponse) }
      def update(payload); end

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String), options: Inttegro::Types::Payload).returns(Inttegro::Models::SecretKeyUsageResponse) }
      def usage(secret_key_id: nil, key_id: nil, id: nil, **options); end

      private

      sig { params(secret_key_id: T.nilable(String), key_id: T.nilable(String), id: T.nilable(String)).returns(Inttegro::Types::Payload) }
      def identifier_payload(secret_key_id, key_id, id); end
    end

    class MessageTemplates
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(template_id: String, idempotency_key: T.nilable(String)).returns(Inttegro::Models::MessageTemplateEnvelope) }
      def archive(template_id:, idempotency_key: nil); end

      sig { params(payload: T.any(Inttegro::Models::CreateMessageTemplateRequest, Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::MessageTemplateEnvelope) }
      def create(payload, idempotency_key: nil); end

      sig { params(template_id: String).returns(Inttegro::Models::MessageTemplateEnvelope) }
      def lookup(template_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageMessageTemplatesRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::MessageTemplatesPageEnvelope) }
      def page(payload = nil); end

      sig { params(template_id: String, idempotency_key: T.nilable(String)).returns(Inttegro::Models::MessageTemplateEnvelope) }
      def publish(template_id:, idempotency_key: nil); end

      sig { params(payload: T.any(Inttegro::Models::RenderMessageTemplatePreviewRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::RenderMessageTemplatePreviewResponse) }
      def render_preview(payload); end

      sig { params(payload: T.any(Inttegro::Models::UpdateMessageTemplateRequest, Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::MessageTemplateEnvelope) }
      def update(payload, idempotency_key: nil); end

      private

      sig { params(idempotency_key: T.nilable(String)).returns(Inttegro::Types::Headers) }
      def idempotency_headers(idempotency_key); end
    end

    class Orders
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(order_id: String, request_meta: T.nilable(Inttegro::Types::Payload)).returns(Inttegro::Models::OrderResponse) }
      def cancel(order_id:, request_meta: nil); end

      sig { params(payload: T.any(Inttegro::Models::CompleteOrderRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::CompleteOrderResponse) }
      def complete(payload); end

      sig { params(payload: T.any(Inttegro::Models::ConfirmPaymentRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::OrderResponse) }
      def confirm_payment(payload); end

      sig { params(payload: T.any(T.any(Inttegro::Models::CreateOrderNewCustomer, Inttegro::Models::CreateOrderExistingCustomer), Inttegro::Types::Payload)).returns(Inttegro::Models::OrderResponse) }
      def create(payload); end

      sig { params(order_id: String, request_meta: T.nilable(Inttegro::Types::Payload)).returns(Inttegro::Models::FinalizeOrderResponse) }
      def finalize(order_id:, request_meta: nil); end

      sig { params(order_id: String, options: Inttegro::Types::Payload).returns(Inttegro::Models::OrderResponse) }
      def lookup(order_id:, **options); end

      sig { params(payload: T.any(T.any(Inttegro::Models::CreateOrderNewCustomer, Inttegro::Models::CreateOrderExistingCustomer), Inttegro::Types::Payload)).returns(Inttegro::Models::OrderResponse) }
      def new(payload); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageOrdersRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PageOrdersResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::PayOrderRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::OrderResponse) }
      def pay(payload); end

      sig { params(payload: T.any(Inttegro::Models::CreateRefundRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::RefundResponse) }
      def refund(payload); end

      sig { params(order_id: String, request_meta: T.nilable(Inttegro::Types::Payload)).returns(Inttegro::Models::OrderResponse) }
      def request_confirmation(order_id:, request_meta: nil); end

      sig { params(order_id: String).returns(Inttegro::Models::OrderDocumentDeliveryResponse) }
      def send_invoice(order_id:); end

      sig { params(order_id: String).returns(Inttegro::Models::OrderDocumentDeliveryResponse) }
      def send_receipt(order_id:); end

      sig { params(payload: T.any(Inttegro::Models::UpdateOrderRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::OrderResponse) }
      def update(payload); end

      private

      sig { params(action: String, order_id: String).returns(Inttegro::Types::Payload) }
      def stable_order_request_meta(action, order_id); end
    end

    class Otp
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: Inttegro::Types::RequestBody).returns(Inttegro::Models::CancelOTPResponse) }
      def cancel(payload); end

      sig { params(payload: T.any(Inttegro::Models::InitiateOTPRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::InitiateOTPResponse) }
      def initiate(payload); end

      sig { params(payload: T.any(Inttegro::Models::LookupOTPRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::LookupOTPResponse) }
      def lookup(payload); end

      sig { params(payload: T.any(Inttegro::Models::VerifyOTPRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::VerifyOTPResponse) }
      def verify(payload); end
    end

    class PaymentMethods
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payment_method_id: String).returns(Inttegro::Models::ActivatePaymentMethodResponse) }
      def activate(payment_method_id:); end

      sig { params(payment_method_id: String).returns(Inttegro::Models::ArchivePaymentMethodResponse) }
      def archive(payment_method_id:); end

      sig { params(payload: Inttegro::Types::RequestBody).returns(Inttegro::Models::PaymentMethodResponse) }
      def confirm_verification(payload); end

      sig { params(payment_method_id: String, request_meta: T.nilable(Inttegro::Types::Payload)).returns(Inttegro::Models::PaymentMethodDeleteResponse) }
      def delete(payment_method_id:, request_meta: nil); end

      sig { params(payment_method_id: String).returns(Inttegro::Models::DisactivatePaymentMethodResponse) }
      def disactivate(payment_method_id:); end

      sig { params(payment_method_id: String).returns(Inttegro::Models::LookupPaymentMethodResponse) }
      def lookup(payment_method_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PaymentMethodPageRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PaymentMethodPageResponse) }
      def page(payload = nil); end

      sig { returns(Inttegro::Models::GetPaymentMethodSettingsResponse) }
      def settings(); end

      sig { params(payload: T.any(Inttegro::Models::TokenizeMobileMoneyPaymentMethodRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::TokenizePaymentMethodResponse) }
      def tokenize(payload); end

      sig { params(payment_method_id: String).returns(Inttegro::Models::UnarchivePaymentMethodResponse) }
      def unarchive(payment_method_id:); end

      sig { params(payload: T.any(Inttegro::Models::UpdatePaymentMethodRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::UpdatePaymentMethodResponse) }
      def update(payload); end

      sig { params(payment_method_id: String, request_meta: T.nilable(Inttegro::Types::Payload)).returns(Inttegro::Models::PaymentMethodVerificationResponse) }
      def verify(payment_method_id:, request_meta: nil); end

      private

      sig { params(action: String, payment_method_id: String).returns(Inttegro::Types::Payload) }
      def stable_payment_method_request_meta(action, payment_method_id); end
    end

    class Payouts
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payout_id: String).returns(Inttegro::Models::CancelPayoutResponse) }
      def cancel(payout_id:); end

      sig { returns(Inttegro::Models::DisableAutomaticPayoutsResponse) }
      def disable_automatic(); end

      sig { returns(Inttegro::Models::PayoutSettingsResponse) }
      def disable_fx(); end

      sig { returns(Inttegro::Models::EnableAutomaticPayoutsResponse) }
      def enable_automatic(); end

      sig { returns(Inttegro::Models::PayoutSettingsResponse) }
      def enable_fx(); end

      sig { params(payout_id: String).returns(Inttegro::Models::LookupPayoutResponse) }
      def lookup(payout_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PagePayoutsRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PagePayoutsResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::SchedulePayoutRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::SchedulePayoutResponse) }
      def schedule(payload); end

      sig { params(destinations: T::Hash[String, String]).returns(Inttegro::Models::SetPayoutDestinationsResponse) }
      def set_destinations(destinations:); end

      sig { returns(Inttegro::Models::GetPayoutSettingsResponse) }
      def settings(); end
    end

    class Prices
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(price_id: String).returns(Inttegro::Models::PriceResponse) }
      def activate(price_id:); end

      sig { params(price_id: String).returns(Inttegro::Models::PriceResponse) }
      def archive(price_id:); end

      sig { params(payload: T.any(Inttegro::Models::CreatePriceRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::PriceResponse) }
      def create(payload); end

      sig { params(price_id: String).returns(Inttegro::Models::PriceResponse) }
      def deactivate(price_id:); end

      sig { params(price_id: String).returns(Inttegro::Models::PriceResponse) }
      def lookup(price_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PricePageRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PricePageResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::UpdatePriceRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::PriceResponse) }
      def update(payload); end
    end

    class Products
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::AddProductPriceRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::AddProductPriceResponse) }
      def add_price(payload); end

      sig { params(product_id: String).returns(Inttegro::Models::ProductResponse) }
      def archive(product_id:); end

      sig { params(payload: T.any(Inttegro::Models::CreateProductRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::ProductResponse) }
      def create(payload); end

      sig { params(product_id: String).returns(Inttegro::Models::ProductResponse) }
      def lookup(product_id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageProductsRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PageProductsResponse) }
      def page(payload = nil); end

      sig { params(product_id: String).returns(Inttegro::Models::ProductResponse) }
      def publish(product_id:); end

      sig { params(payload: T.any(Inttegro::Models::SetDefaultUnitPriceRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::ProductResponse) }
      def set_default_unit_price(payload); end

      sig { params(product_id: String).returns(Inttegro::Models::ProductResponse) }
      def unpublish(product_id:); end

      sig { params(payload: T.any(Inttegro::Models::UpdateProductRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::UpdateProductResponse) }
      def update(payload); end
    end

    class PurchaseIntents
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(id: String).returns(Inttegro::Models::PurchaseIntentResponse) }
      def cancel(id:); end

      sig { params(payload: T.any(Inttegro::Models::CreatePurchaseIntentRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::PurchaseIntentResponse) }
      def create(payload); end

      sig { params(id: String).returns(Inttegro::Models::PurchaseIntentResponse) }
      def lookup(id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PagePurchaseIntentsRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::PagePurchaseIntentsResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::UpdatePurchaseIntentRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::PurchaseIntentResponse) }
      def update(payload); end
    end

    class Refunds
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(refund_id: String).returns(Inttegro::Models::RefundResponse) }
      def cancel(refund_id:); end

      sig { params(payload: T.any(Inttegro::Models::CreateRefundRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::RefundResponse) }
      def create(payload); end

      sig { params(refund_id: String).returns(Inttegro::Models::RefundResponse) }
      def lookup(refund_id:); end

      sig { params(payload: T.any(Inttegro::Models::PageRefundsRequest, Inttegro::Types::Payload)).returns(Inttegro::Models::RefundPageResponse) }
      def page(payload); end
    end

    class Schedules
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(schedule_id: String).returns(Inttegro::Models::ScheduleCancelResponse) }
      def cancel(schedule_id:); end

      sig { params(schedule_id: String).returns(Inttegro::Models::ScheduleLookupResponse) }
      def lookup(schedule_id:); end
    end

    class Spec
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { returns(Inttegro::Models::ListCountrySpecsResponse) }
      def countries(); end
    end

    class UploadRequests
      sig { params(http: Inttegro::HTTPClient).void }
      def initialize(http); end

      sig { params(payload: T.any(Inttegro::Models::CancelUploadRequestRequest, Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::UploadRequestResponse) }
      def cancel(payload, idempotency_key: nil); end

      sig { params(payload: T.any(Inttegro::Models::CreateUploadRequestRequest, Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::UploadRequestResponse) }
      def create(payload, idempotency_key: nil); end

      sig { params(upload_url: String, file: String).returns(Inttegro::Models::FulfillUploadRequestResponse) }
      def fulfill(upload_url:, file:); end

      sig { params(id: String).returns(Inttegro::Models::UploadRequestWithAttemptResponse) }
      def lookup(id:); end

      sig { params(payload: T.nilable(T.any(Inttegro::Models::PageUploadRequestsRequest, Inttegro::Types::Payload))).returns(Inttegro::Models::UploadRequestPageResponse) }
      def page(payload = nil); end

      sig { params(payload: T.any(Inttegro::Models::ReviewUploadRequestAttemptRequest, Inttegro::Types::Payload), idempotency_key: T.nilable(String)).returns(Inttegro::Models::UploadRequestWithAttemptResponse) }
      def review(payload, idempotency_key: nil); end

      private

      sig { params(idempotency_key: T.nilable(String)).returns(Inttegro::Types::Headers) }
      def headers(idempotency_key); end
    end
  end
end
